apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: fraud-api
  version: "1.0"

images:
  - name: fraud-api
    newTag: "1.0"